apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  labels:
    app: gpu-test
spec:
  # Node Selector - Target GPU nodes
  nodeSelector:
    node-type: gpu
  
  # Tolerations - Match the GPU taint
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  
  # Restart policy
  restartPolicy: Never
  
  containers:
    - name: cuda-test
      image: nvidia/cuda:11.0.3-base-ubuntu20.04
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "=== GPU Test Pod Started ==="
          echo "Checking NVIDIA GPU availability..."
          nvidia-smi
          echo ""
          echo "=== GPU Details ==="
          nvidia-smi -L
          echo ""
          echo "=== Sleeping for 1 hour to keep pod running ==="
          sleep 3600
      
      # GPU Resource Request
      resources:
        requests:
          nvidia.com/gpu: 1
        limits:
          nvidia.com/gpu: 1
