apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-gen
  namespace: monitoring
  labels:
    app: trace-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-gen
  template:
    metadata:
      labels:
        app: trace-gen
    spec:
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args:
        - traces
        - --otlp-endpoint=tempo.monitoring.svc.cluster.local:4317
        - --otlp-insecure
        - --rate=10
        - --duration=1000h
