apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  labels:
    app: gpu-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.0.0-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1 # Requesting 1 Virtual Slice
